title: Somewhen Storytelling Festival, 2023
preposition: at
description: >-
  A celebration of storytelling as living oral culture. __Tales for all ages.__ *Because stories aren't (just) for children.*
baseurl: "/somewhen-festival-2023" # the subpath of your site, e.g. /blog
url: "https://ouseful-testing.github.io" # the base hostname & protocol for your site, e.g. https://example.com
github_username:  ouseful-testing
timezone: Europe/London

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference"

# Build settings
plugins:
  [jekyll-include-cache]
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml
  - vendor

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: SomewhenLogo
      img: 'SOMEWHEN_LOGO_V2_small_transparent.png'
      #url: 'https://digitale-gesellschaft.ch/'
    links:
      - name: Program
        relative_url: /program/
        disabled: false
      - name: Performances
        relative_url: /talks/
#      - name: Performances
#        relative_url: /performances/
      - name: Tellers
        relative_url: /speakers/
#      - name: Tellers
#        relative_url: /tellers/
      - name: Location
        relative_url: /location/
      - name: Print Programme
        relative_url: /print-programme/
      - name: Crew
        relative_url: /crew/
        disabled: true
#      - name: Register/Submit Abstract
#        #relative_url: /register/
#        absolute_url: 'https://docs.google.com/forms/d/e/1FAIpQLSeDlADcAg67SqH-oKPWU1LCDTU1WiNBEPfftLJnPFGz-oc_Ew/viewform?usp=sf_link'
#        disabled: false
#      - name: Previous Editions
#        menu:
#          - name: 2023 (current)
#            disabled: true
#          - name: 2022
#            relative_url: https://vibe2022.github.io/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    img: ''
    links:
      - name: Program
        relative_url: /program/
        disabled: true
      - name: How to get here
        relative_url: /location/
      - name: Tickets
        disabled: false
        absolute_url: 'https://www.ticketsource.co.uk/somewhen-storytelling-festival'

# Information boxes
  info_bars:
#   - title: Now calling for volunteers
#     color: primary
#     main_only: false
#     text: |
#       If you would like to volunteer to help run the festival, please email volunteers@tistales.org.uk
    - title: Travel disruption
      color: primary
      main_only: false
      text: |
        There are road closures in Havenstreet — access to the festival site is from the Briddlesford Road

  # Live indications
#  live:
#    date: 09.06.2022
#    timezone: Europe/Dublin
#    stop:       240  # in minutes
#    streaming:
#      enable: false
#      pause:     60  # in minutes
#      prepend:    5  # in minutes
#      extend:     5  # in minutes
#    demo:
#      enable: false
#      duration: 300  # in seconds
#      pause:     10  # in seconds


  talks:
    # Talk categories
    main_categories:
      - name: Storytelling
        color: info 
      - name: Story shorts (15min)
        color: warning 
      - name: Story circle
        color: success
      - name: Talk
        color: secondary
      - name: Music
        color: danger
      - name: Other attraction
        color: danger
      - name: Walkabout
        color: warning
      - name: Workshop
        color: dark

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true
    
  location:
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Disable links to locations
    hide: false
    map:
      # show map
      enable: true
      # initial map center point
      home_coord: 50.7051893, -1.2167519
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Hydda.Full
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 10
 
  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
